import { createThemeContract, createTheme } from '@vanilla-extract/css'
import { tokens } from './tokens.css.ts'

export const vars = createThemeContract({
  color: {
    brand: null,
    brandSoft: null,
    background: null,
    surface: null,
    surfaceMuted: null,
    text: null,
    textMuted: null,
    textInverse: null,
    border: null,
    danger: null,
    warning: null,
    success: null,
    info: null,
    overlay: null,
  },
  space: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    8: null,
    10: null,
    12: null,
  },
  radius: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },
  fontSize: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
  },
  fontWeight: {
    regular: null,
    medium: null,
    semibold: null,
    bold: null,
  },
  lineHeight: {
    tight: null,
    normal: null,
    relaxed: null,
  },
  shadow: {
    sm: null,
    md: null,
    lg: null,
  },
  zIndex: {
    base: null,
    dropdown: null,
    sticky: null,
    overlay: null,
    modal: null,
    toast: null,
  },
  size: {
    touch: null,
    header: null,
    bottomNav: null,
  },
  duration: {
    fast: null,
    normal: null,
    slow: null,
  },
})

export const lightTheme = createTheme(vars, {
  color: {
    brand: tokens.color.brand[600],
    brandSoft: tokens.color.brand[50],
    background: tokens.color.gray[50],
    surface: tokens.color.white,
    surfaceMuted: tokens.color.gray[100],
    text: tokens.color.gray[900],
    textMuted: tokens.color.gray[600],
    textInverse: tokens.color.white,
    border: tokens.color.gray[200],
    danger: tokens.color.danger,
    warning: tokens.color.warning,
    success: tokens.color.success,
    info: tokens.color.info,
    overlay: 'rgba(33, 37, 41, 0.48)',
  },
  space: { ...tokens.space },
  radius: { ...tokens.radius },
  fontSize: { ...tokens.fontSize },
  fontWeight: { ...tokens.fontWeight },
  lineHeight: { ...tokens.lineHeight },
  shadow: { ...tokens.shadow },
  zIndex: {
    base: String(tokens.zIndex.base),
    dropdown: String(tokens.zIndex.dropdown),
    sticky: String(tokens.zIndex.sticky),
    overlay: String(tokens.zIndex.overlay),
    modal: String(tokens.zIndex.modal),
    toast: String(tokens.zIndex.toast),
  },
  size: { ...tokens.size },
  duration: { ...tokens.duration },
})
